/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BroadcastTxRequest model module.
 * @module model/BroadcastTxRequest
 * @version 1.2.1
 */
class BroadcastTxRequest {
    /**
     * Constructs a new <code>BroadcastTxRequest</code>.
     * @alias module:model/BroadcastTxRequest
     * @param txHex {String} Signed raw tx hex to broadcast
     */
    constructor(txHex) { 
        
        BroadcastTxRequest.initialize(this, txHex);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, txHex) { 
        obj['txHex'] = txHex;
    }

    /**
     * Constructs a <code>BroadcastTxRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BroadcastTxRequest} obj Optional instance to populate.
     * @return {module:model/BroadcastTxRequest} The populated <code>BroadcastTxRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BroadcastTxRequest();

            if (data.hasOwnProperty('txHex')) {
                obj['txHex'] = ApiClient.convertToType(data['txHex'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Signed raw tx hex to broadcast
 * @member {String} txHex
 */
BroadcastTxRequest.prototype['txHex'] = undefined;






export default BroadcastTxRequest;

