/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BurnTokenRequestBurn', 'model/SendTokenRequestTo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BurnTokenRequestBurn'), require('./SendTokenRequestTo'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.BurnTokenRequest = factory(root.NeblioRestApiSuite.ApiClient, root.NeblioRestApiSuite.BurnTokenRequestBurn, root.NeblioRestApiSuite.SendTokenRequestTo);
  }
}(this, function(ApiClient, BurnTokenRequestBurn, SendTokenRequestTo) {
  'use strict';




  /**
   * The BurnTokenRequest model module.
   * @module model/BurnTokenRequest
   * @version 1.1.1
   */

  /**
   * Constructs a new <code>BurnTokenRequest</code>.
   * @alias module:model/BurnTokenRequest
   * @class
   * @param fee {Number} Fee in satoshi to include in the issuance transaction min 10000 (0.0001 NEBL)
   * @param burn {Array.<module:model/BurnTokenRequestBurn>} Array of objects representing tokens to be burned
   */
  var exports = function(fee, burn) {
    var _this = this;

    _this['fee'] = fee;


    _this['burn'] = burn;
  };

  /**
   * Constructs a <code>BurnTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BurnTokenRequest} obj Optional instance to populate.
   * @return {module:model/BurnTokenRequest} The populated <code>BurnTokenRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fee')) {
        obj['fee'] = ApiClient.convertToType(data['fee'], 'Number');
      }
      if (data.hasOwnProperty('from')) {
        obj['from'] = ApiClient.convertToType(data['from'], ['String']);
      }
      if (data.hasOwnProperty('transfer')) {
        obj['transfer'] = ApiClient.convertToType(data['transfer'], [SendTokenRequestTo]);
      }
      if (data.hasOwnProperty('burn')) {
        obj['burn'] = ApiClient.convertToType(data['burn'], [BurnTokenRequestBurn]);
      }
    }
    return obj;
  }

  /**
   * Fee in satoshi to include in the issuance transaction min 10000 (0.0001 NEBL)
   * @member {Number} fee
   */
  exports.prototype['fee'] = undefined;
  /**
   * Array of addresses to send the token from
   * @member {Array.<String>} from
   */
  exports.prototype['from'] = undefined;
  /**
   * @member {Array.<module:model/SendTokenRequestTo>} transfer
   */
  exports.prototype['transfer'] = undefined;
  /**
   * Array of objects representing tokens to be burned
   * @member {Array.<module:model/BurnTokenRequestBurn>} burn
   */
  exports.prototype['burn'] = undefined;



  return exports;
}));


