/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.BurnTokenRequestBurn = factory(root.NeblioRestApiSuite.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BurnTokenRequestBurn model module.
   * @module model/BurnTokenRequestBurn
   * @version 1.1.1
   */

  /**
   * Constructs a new <code>BurnTokenRequestBurn</code>.
   * @alias module:model/BurnTokenRequestBurn
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>BurnTokenRequestBurn</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BurnTokenRequestBurn} obj Optional instance to populate.
   * @return {module:model/BurnTokenRequestBurn} The populated <code>BurnTokenRequestBurn</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('tokenId')) {
        obj['tokenId'] = ApiClient.convertToType(data['tokenId'], 'String');
      }
    }
    return obj;
  }

  /**
   * Amount of tokens to burn
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * Unique token id we are burning
   * @member {String} tokenId
   */
  exports.prototype['tokenId'] = undefined;



  return exports;
}));


