/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.GetAddressInfoResponseTokens = factory(root.NeblioRestApiSuite.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetAddressInfoResponseTokens model module.
   * @module model/GetAddressInfoResponseTokens
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>GetAddressInfoResponseTokens</code>.
   * @alias module:model/GetAddressInfoResponseTokens
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>GetAddressInfoResponseTokens</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAddressInfoResponseTokens} obj Optional instance to populate.
   * @return {module:model/GetAddressInfoResponseTokens} The populated <code>GetAddressInfoResponseTokens</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tokenId')) {
        obj['tokenId'] = ApiClient.convertToType(data['tokenId'], 'String');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('issueTxid')) {
        obj['issueTxid'] = ApiClient.convertToType(data['issueTxid'], 'String');
      }
      if (data.hasOwnProperty('divisibility')) {
        obj['divisibility'] = ApiClient.convertToType(data['divisibility'], 'Number');
      }
      if (data.hasOwnProperty('lockStatus')) {
        obj['lockStatus'] = ApiClient.convertToType(data['lockStatus'], 'Boolean');
      }
      if (data.hasOwnProperty('aggregationPolicy')) {
        obj['aggregationPolicy'] = ApiClient.convertToType(data['aggregationPolicy'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique NTP1 identifier for this token
   * @member {String} tokenId
   */
  exports.prototype['tokenId'] = undefined;
  /**
   * Number of Tokens
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * TXID the token originally was issued in
   * @member {String} issueTxid
   */
  exports.prototype['issueTxid'] = undefined;
  /**
   * Decimal places the token is divisible to
   * @member {Number} divisibility
   */
  exports.prototype['divisibility'] = undefined;
  /**
   * Whether the token is locked, preventing more from being issued
   * @member {Boolean} lockStatus
   */
  exports.prototype['lockStatus'] = undefined;
  /**
   * Whether the tokens can be aggregated together
   * @member {String} aggregationPolicy
   */
  exports.prototype['aggregationPolicy'] = undefined;



  return exports;
}));


