/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetAddressResponse model module.
 * @module model/GetAddressResponse
 * @version 1.2.1
 */
class GetAddressResponse {
    /**
     * Constructs a new <code>GetAddressResponse</code>.
     * @alias module:model/GetAddressResponse
     */
    constructor() { 
        
        GetAddressResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetAddressResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAddressResponse} obj Optional instance to populate.
     * @return {module:model/GetAddressResponse} The populated <code>GetAddressResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAddressResponse();

            if (data.hasOwnProperty('addrStr')) {
                obj['addrStr'] = ApiClient.convertToType(data['addrStr'], 'String');
            }
            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
            if (data.hasOwnProperty('balanceSat')) {
                obj['balanceSat'] = ApiClient.convertToType(data['balanceSat'], 'Number');
            }
            if (data.hasOwnProperty('totalReceived')) {
                obj['totalReceived'] = ApiClient.convertToType(data['totalReceived'], 'Number');
            }
            if (data.hasOwnProperty('totalReceivedSat')) {
                obj['totalReceivedSat'] = ApiClient.convertToType(data['totalReceivedSat'], 'Number');
            }
            if (data.hasOwnProperty('totalSent')) {
                obj['totalSent'] = ApiClient.convertToType(data['totalSent'], 'Number');
            }
            if (data.hasOwnProperty('totalSentSat')) {
                obj['totalSentSat'] = ApiClient.convertToType(data['totalSentSat'], 'Number');
            }
            if (data.hasOwnProperty('unconfirmedBalance')) {
                obj['unconfirmedBalance'] = ApiClient.convertToType(data['unconfirmedBalance'], 'Number');
            }
            if (data.hasOwnProperty('unconfirmedBalanceSat')) {
                obj['unconfirmedBalanceSat'] = ApiClient.convertToType(data['unconfirmedBalanceSat'], 'Number');
            }
            if (data.hasOwnProperty('unconfirmedTxAppearances')) {
                obj['unconfirmedTxAppearances'] = ApiClient.convertToType(data['unconfirmedTxAppearances'], 'Number');
            }
            if (data.hasOwnProperty('txAppearances')) {
                obj['txAppearances'] = ApiClient.convertToType(data['txAppearances'], 'Number');
            }
            if (data.hasOwnProperty('transactions')) {
                obj['transactions'] = ApiClient.convertToType(data['transactions'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Address in string form
 * @member {String} addrStr
 */
GetAddressResponse.prototype['addrStr'] = undefined;

/**
 * NEBL balance
 * @member {Number} balance
 */
GetAddressResponse.prototype['balance'] = undefined;

/**
 * NEBL balance in satoshis
 * @member {Number} balanceSat
 */
GetAddressResponse.prototype['balanceSat'] = undefined;

/**
 * Total NEBL received
 * @member {Number} totalReceived
 */
GetAddressResponse.prototype['totalReceived'] = undefined;

/**
 * Total NEBL received in satoshis
 * @member {Number} totalReceivedSat
 */
GetAddressResponse.prototype['totalReceivedSat'] = undefined;

/**
 * Total NEBL sent
 * @member {Number} totalSent
 */
GetAddressResponse.prototype['totalSent'] = undefined;

/**
 * Total NEBL sent satoshis
 * @member {Number} totalSentSat
 */
GetAddressResponse.prototype['totalSentSat'] = undefined;

/**
 * Unconfirmed NEBL balance
 * @member {Number} unconfirmedBalance
 */
GetAddressResponse.prototype['unconfirmedBalance'] = undefined;

/**
 * Unconfirmed NEBL balance in satoshis
 * @member {Number} unconfirmedBalanceSat
 */
GetAddressResponse.prototype['unconfirmedBalanceSat'] = undefined;

/**
 * Number of unconfirmed transactions for this address
 * @member {Number} unconfirmedTxAppearances
 */
GetAddressResponse.prototype['unconfirmedTxAppearances'] = undefined;

/**
 * Number of transactions for this address
 * @member {Number} txAppearances
 */
GetAddressResponse.prototype['txAppearances'] = undefined;

/**
 * Array of transaction ids for this address
 * @member {Array.<String>} transactions
 */
GetAddressResponse.prototype['transactions'] = undefined;






export default GetAddressResponse;

