/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.GetAddressUtxosResponseInner = factory(root.NeblioRestApiSuite.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetAddressUtxosResponseInner model module.
   * @module model/GetAddressUtxosResponseInner
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>GetAddressUtxosResponseInner</code>.
   * @alias module:model/GetAddressUtxosResponseInner
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>GetAddressUtxosResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAddressUtxosResponseInner} obj Optional instance to populate.
   * @return {module:model/GetAddressUtxosResponseInner} The populated <code>GetAddressUtxosResponseInner</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('txid')) {
        obj['txid'] = ApiClient.convertToType(data['txid'], 'String');
      }
      if (data.hasOwnProperty('vout')) {
        obj['vout'] = ApiClient.convertToType(data['vout'], 'Number');
      }
      if (data.hasOwnProperty('ts')) {
        obj['ts'] = ApiClient.convertToType(data['ts'], 'Number');
      }
      if (data.hasOwnProperty('scriptPubKey')) {
        obj['scriptPubKey'] = ApiClient.convertToType(data['scriptPubKey'], 'String');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('confirmations')) {
        obj['confirmations'] = ApiClient.convertToType(data['confirmations'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Address
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * Transaction ID
   * @member {String} txid
   */
  exports.prototype['txid'] = undefined;
  /**
   * vout
   * @member {Number} vout
   */
  exports.prototype['vout'] = undefined;
  /**
   * Timestamp
   * @member {Number} ts
   */
  exports.prototype['ts'] = undefined;
  /**
   * scriptPubKey
   * @member {String} scriptPubKey
   */
  exports.prototype['scriptPubKey'] = undefined;
  /**
   * NEBL amount
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * Number of confirmations
   * @member {Number} confirmations
   */
  exports.prototype['confirmations'] = undefined;



  return exports;
}));


