/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.GetAddressResponse = factory(root.NeblioRestApiSuite.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetAddressResponse model module.
   * @module model/GetAddressResponse
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>GetAddressResponse</code>.
   * @alias module:model/GetAddressResponse
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>GetAddressResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAddressResponse} obj Optional instance to populate.
   * @return {module:model/GetAddressResponse} The populated <code>GetAddressResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('addrStr')) {
        obj['addrStr'] = ApiClient.convertToType(data['addrStr'], 'String');
      }
      if (data.hasOwnProperty('balance')) {
        obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
      }
      if (data.hasOwnProperty('balanceSat')) {
        obj['balanceSat'] = ApiClient.convertToType(data['balanceSat'], 'Number');
      }
      if (data.hasOwnProperty('totalReceived')) {
        obj['totalReceived'] = ApiClient.convertToType(data['totalReceived'], 'Number');
      }
      if (data.hasOwnProperty('totalReceivedSat')) {
        obj['totalReceivedSat'] = ApiClient.convertToType(data['totalReceivedSat'], 'Number');
      }
      if (data.hasOwnProperty('totalSent')) {
        obj['totalSent'] = ApiClient.convertToType(data['totalSent'], 'Number');
      }
      if (data.hasOwnProperty('totalSentSat')) {
        obj['totalSentSat'] = ApiClient.convertToType(data['totalSentSat'], 'Number');
      }
      if (data.hasOwnProperty('unconfirmedBalance')) {
        obj['unconfirmedBalance'] = ApiClient.convertToType(data['unconfirmedBalance'], 'Number');
      }
      if (data.hasOwnProperty('unconfirmedBalanceSat')) {
        obj['unconfirmedBalanceSat'] = ApiClient.convertToType(data['unconfirmedBalanceSat'], 'Number');
      }
      if (data.hasOwnProperty('unconfirmedTxAppearances')) {
        obj['unconfirmedTxAppearances'] = ApiClient.convertToType(data['unconfirmedTxAppearances'], 'Number');
      }
      if (data.hasOwnProperty('txAppearances')) {
        obj['txAppearances'] = ApiClient.convertToType(data['txAppearances'], 'Number');
      }
      if (data.hasOwnProperty('transactions')) {
        obj['transactions'] = ApiClient.convertToType(data['transactions'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Address in string form
   * @member {String} addrStr
   */
  exports.prototype['addrStr'] = undefined;
  /**
   * NEBL balance
   * @member {Number} balance
   */
  exports.prototype['balance'] = undefined;
  /**
   * NEBL balance in satoshis
   * @member {Number} balanceSat
   */
  exports.prototype['balanceSat'] = undefined;
  /**
   * Total NEBL received
   * @member {Number} totalReceived
   */
  exports.prototype['totalReceived'] = undefined;
  /**
   * Total NEBL received in satoshis
   * @member {Number} totalReceivedSat
   */
  exports.prototype['totalReceivedSat'] = undefined;
  /**
   * Total NEBL sent
   * @member {Number} totalSent
   */
  exports.prototype['totalSent'] = undefined;
  /**
   * Total NEBL sent satoshis
   * @member {Number} totalSentSat
   */
  exports.prototype['totalSentSat'] = undefined;
  /**
   * Unconfirmed NEBL balance
   * @member {Number} unconfirmedBalance
   */
  exports.prototype['unconfirmedBalance'] = undefined;
  /**
   * Unconfirmed NEBL balance in satoshis
   * @member {Number} unconfirmedBalanceSat
   */
  exports.prototype['unconfirmedBalanceSat'] = undefined;
  /**
   * Number of unconfirmed transactions for this address
   * @member {Number} unconfirmedTxAppearances
   */
  exports.prototype['unconfirmedTxAppearances'] = undefined;
  /**
   * Number of transactions for this address
   * @member {Number} txAppearances
   */
  exports.prototype['txAppearances'] = undefined;
  /**
   * Array of transaction ids for this address
   * @member {Array.<String>} transactions
   */
  exports.prototype['transactions'] = undefined;



  return exports;
}));


