/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetBlockIndexResponse model module.
 * @module model/GetBlockIndexResponse
 * @version 1.2.1
 */
class GetBlockIndexResponse {
    /**
     * Constructs a new <code>GetBlockIndexResponse</code>.
     * @alias module:model/GetBlockIndexResponse
     */
    constructor() { 
        
        GetBlockIndexResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetBlockIndexResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetBlockIndexResponse} obj Optional instance to populate.
     * @return {module:model/GetBlockIndexResponse} The populated <code>GetBlockIndexResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetBlockIndexResponse();

            if (data.hasOwnProperty('blockHash')) {
                obj['blockHash'] = ApiClient.convertToType(data['blockHash'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Hash of the requested block
 * @member {String} blockHash
 */
GetBlockIndexResponse.prototype['blockHash'] = undefined;






export default GetBlockIndexResponse;

