/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetFaucetResponseData model module.
 * @module model/GetFaucetResponseData
 * @version 1.2.1
 */
class GetFaucetResponseData {
    /**
     * Constructs a new <code>GetFaucetResponseData</code>.
     * @alias module:model/GetFaucetResponseData
     */
    constructor() { 
        
        GetFaucetResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetFaucetResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetFaucetResponseData} obj Optional instance to populate.
     * @return {module:model/GetFaucetResponseData} The populated <code>GetFaucetResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetFaucetResponseData();

            if (data.hasOwnProperty('txId')) {
                obj['txId'] = ApiClient.convertToType(data['txId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * TXID of a successful withdrawal
 * @member {String} txId
 */
GetFaucetResponseData.prototype['txId'] = undefined;






export default GetFaucetResponseData;

