/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetFaucetResponseData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetFaucetResponseData'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.GetFaucetResponse = factory(root.NeblioRestApiSuite.ApiClient, root.NeblioRestApiSuite.GetFaucetResponseData);
  }
}(this, function(ApiClient, GetFaucetResponseData) {
  'use strict';




  /**
   * The GetFaucetResponse model module.
   * @module model/GetFaucetResponse
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>GetFaucetResponse</code>.
   * @alias module:model/GetFaucetResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>GetFaucetResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetFaucetResponse} obj Optional instance to populate.
   * @return {module:model/GetFaucetResponse} The populated <code>GetFaucetResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = GetFaucetResponseData.constructFromObject(data['data']);
      }
    }
    return obj;
  }

  /**
   * Whether the withdrawal was successful
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {module:model/GetFaucetResponseData} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


