/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetRawTxResponse model module.
 * @module model/GetRawTxResponse
 * @version 1.2.1
 */
class GetRawTxResponse {
    /**
     * Constructs a new <code>GetRawTxResponse</code>.
     * @alias module:model/GetRawTxResponse
     */
    constructor() { 
        
        GetRawTxResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetRawTxResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRawTxResponse} obj Optional instance to populate.
     * @return {module:model/GetRawTxResponse} The populated <code>GetRawTxResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRawTxResponse();

            if (data.hasOwnProperty('rawtx')) {
                obj['rawtx'] = ApiClient.convertToType(data['rawtx'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Raw hex representing the transaction
 * @member {String} rawtx
 */
GetRawTxResponse.prototype['rawtx'] = undefined;






export default GetRawTxResponse;

