/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetSyncResponse model module.
 * @module model/GetSyncResponse
 * @version 1.2.1
 */
class GetSyncResponse {
    /**
     * Constructs a new <code>GetSyncResponse</code>.
     * Object containing node sync status
     * @alias module:model/GetSyncResponse
     */
    constructor() { 
        
        GetSyncResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetSyncResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSyncResponse} obj Optional instance to populate.
     * @return {module:model/GetSyncResponse} The populated <code>GetSyncResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSyncResponse();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('blockChainHeight')) {
                obj['blockChainHeight'] = ApiClient.convertToType(data['blockChainHeight'], 'Number');
            }
            if (data.hasOwnProperty('syncPercentage')) {
                obj['syncPercentage'] = ApiClient.convertToType(data['syncPercentage'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Current sync status
 * @member {String} status
 */
GetSyncResponse.prototype['status'] = undefined;

/**
 * Current blockchain height
 * @member {Number} blockChainHeight
 */
GetSyncResponse.prototype['blockChainHeight'] = undefined;

/**
 * Current sync percentage
 * @member {Number} syncPercentage
 */
GetSyncResponse.prototype['syncPercentage'] = undefined;

/**
 * Height node is synced to
 * @member {Number} height
 */
GetSyncResponse.prototype['height'] = undefined;

/**
 * Recent sync error messages
 * @member {String} error
 */
GetSyncResponse.prototype['error'] = undefined;

/**
 * Node type
 * @member {String} type
 */
GetSyncResponse.prototype['type'] = undefined;






export default GetSyncResponse;

