/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetTransactionInfoResponsePreviousOutput'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetTransactionInfoResponsePreviousOutput'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.GetTxResponseVout = factory(root.NeblioRestApiSuite.ApiClient, root.NeblioRestApiSuite.GetTransactionInfoResponsePreviousOutput);
  }
}(this, function(ApiClient, GetTransactionInfoResponsePreviousOutput) {
  'use strict';




  /**
   * The GetTxResponseVout model module.
   * @module model/GetTxResponseVout
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>GetTxResponseVout</code>.
   * @alias module:model/GetTxResponseVout
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>GetTxResponseVout</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetTxResponseVout} obj Optional instance to populate.
   * @return {module:model/GetTxResponseVout} The populated <code>GetTxResponseVout</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'Number');
      }
      if (data.hasOwnProperty('n')) {
        obj['n'] = ApiClient.convertToType(data['n'], 'Number');
      }
      if (data.hasOwnProperty('scriptPubKey')) {
        obj['scriptPubKey'] = GetTransactionInfoResponsePreviousOutput.constructFromObject(data['scriptPubKey']);
      }
      if (data.hasOwnProperty('used')) {
        obj['used'] = ApiClient.convertToType(data['used'], 'Boolean');
      }
      if (data.hasOwnProperty('blockheight')) {
        obj['blockheight'] = ApiClient.convertToType(data['blockheight'], 'Number');
      }
      if (data.hasOwnProperty('usedBlockheight')) {
        obj['usedBlockheight'] = ApiClient.convertToType(data['usedBlockheight'], 'Number');
      }
      if (data.hasOwnProperty('usedTxid')) {
        obj['usedTxid'] = ApiClient.convertToType(data['usedTxid'], 'String');
      }
    }
    return obj;
  }

  /**
   * Value of the output in NEBL
   * @member {Number} value
   */
  exports.prototype['value'] = undefined;
  /**
   * Output index
   * @member {Number} n
   */
  exports.prototype['n'] = undefined;
  /**
   * @member {module:model/GetTransactionInfoResponsePreviousOutput} scriptPubKey
   */
  exports.prototype['scriptPubKey'] = undefined;
  /**
   * Whether this output has now been used
   * @member {Boolean} used
   */
  exports.prototype['used'] = undefined;
  /**
   * Blockheight of this transaction
   * @member {Number} blockheight
   */
  exports.prototype['blockheight'] = undefined;
  /**
   * Blockheight this output was used in
   * @member {Number} usedBlockheight
   */
  exports.prototype['usedBlockheight'] = undefined;
  /**
   * TXID this output was used in
   * @member {String} usedTxid
   */
  exports.prototype['usedTxid'] = undefined;



  return exports;
}));


