/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetTransactionInfoResponsePreviousOutput model module.
 * @module model/GetTransactionInfoResponsePreviousOutput
 * @version 1.2.1
 */
class GetTransactionInfoResponsePreviousOutput {
    /**
     * Constructs a new <code>GetTransactionInfoResponsePreviousOutput</code>.
     * @alias module:model/GetTransactionInfoResponsePreviousOutput
     */
    constructor() { 
        
        GetTransactionInfoResponsePreviousOutput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetTransactionInfoResponsePreviousOutput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTransactionInfoResponsePreviousOutput} obj Optional instance to populate.
     * @return {module:model/GetTransactionInfoResponsePreviousOutput} The populated <code>GetTransactionInfoResponsePreviousOutput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTransactionInfoResponsePreviousOutput();

            if (data.hasOwnProperty('asm')) {
                obj['asm'] = ApiClient.convertToType(data['asm'], 'String');
            }
            if (data.hasOwnProperty('hex')) {
                obj['hex'] = ApiClient.convertToType(data['hex'], 'String');
            }
            if (data.hasOwnProperty('reqSigs')) {
                obj['reqSigs'] = ApiClient.convertToType(data['reqSigs'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('addresses')) {
                obj['addresses'] = ApiClient.convertToType(data['addresses'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} asm
 */
GetTransactionInfoResponsePreviousOutput.prototype['asm'] = undefined;

/**
 * @member {String} hex
 */
GetTransactionInfoResponsePreviousOutput.prototype['hex'] = undefined;

/**
 * @member {Number} reqSigs
 */
GetTransactionInfoResponsePreviousOutput.prototype['reqSigs'] = undefined;

/**
 * @member {String} type
 */
GetTransactionInfoResponsePreviousOutput.prototype['type'] = undefined;

/**
 * @member {Array.<String>} addresses
 */
GetTransactionInfoResponsePreviousOutput.prototype['addresses'] = undefined;






export default GetTransactionInfoResponsePreviousOutput;

