/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetTxResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetTxResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.GetTxsResponse = factory(root.NeblioRestApiSuite.ApiClient, root.NeblioRestApiSuite.GetTxResponse);
  }
}(this, function(ApiClient, GetTxResponse) {
  'use strict';




  /**
   * The GetTxsResponse model module.
   * @module model/GetTxsResponse
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>GetTxsResponse</code>.
   * Object containing an array of transaction objects
   * @alias module:model/GetTxsResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>GetTxsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetTxsResponse} obj Optional instance to populate.
   * @return {module:model/GetTxsResponse} The populated <code>GetTxsResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pagesTotal')) {
        obj['pagesTotal'] = ApiClient.convertToType(data['pagesTotal'], 'Number');
      }
      if (data.hasOwnProperty('txs')) {
        obj['txs'] = ApiClient.convertToType(data['txs'], [GetTxResponse]);
      }
    }
    return obj;
  }

  /**
   * Number of pages of transactions
   * @member {Number} pagesTotal
   */
  exports.prototype['pagesTotal'] = undefined;
  /**
   * Array of transaction objects
   * @member {Array.<module:model/GetTxResponse>} txs
   */
  exports.prototype['txs'] = undefined;



  return exports;
}));


