/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetTokenHoldersResponseHolders'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetTokenHoldersResponseHolders'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.GetTokenHoldersResponse = factory(root.NeblioRestApiSuite.ApiClient, root.NeblioRestApiSuite.GetTokenHoldersResponseHolders);
  }
}(this, function(ApiClient, GetTokenHoldersResponseHolders) {
  'use strict';




  /**
   * The GetTokenHoldersResponse model module.
   * @module model/GetTokenHoldersResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GetTokenHoldersResponse</code>.
   * @alias module:model/GetTokenHoldersResponse
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>GetTokenHoldersResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetTokenHoldersResponse} obj Optional instance to populate.
   * @return {module:model/GetTokenHoldersResponse} The populated <code>GetTokenHoldersResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tokenId')) {
        obj['tokenId'] = ApiClient.convertToType(data['tokenId'], 'String');
      }
      if (data.hasOwnProperty('holders')) {
        obj['holders'] = ApiClient.convertToType(data['holders'], [GetTokenHoldersResponseHolders]);
      }
      if (data.hasOwnProperty('divibility')) {
        obj['divibility'] = ApiClient.convertToType(data['divibility'], 'Number');
      }
      if (data.hasOwnProperty('lockStatus')) {
        obj['lockStatus'] = ApiClient.convertToType(data['lockStatus'], 'Boolean');
      }
      if (data.hasOwnProperty('aggregationPolicy')) {
        obj['aggregationPolicy'] = ApiClient.convertToType(data['aggregationPolicy'], 'String');
      }
      if (data.hasOwnProperty('someUtxo')) {
        obj['someUtxo'] = ApiClient.convertToType(data['someUtxo'], 'String');
      }
    }
    return obj;
  }

  /**
   * TokenId of the token
   * @member {String} tokenId
   */
  exports.prototype['tokenId'] = undefined;
  /**
   * @member {Array.<module:model/GetTokenHoldersResponseHolders>} holders
   */
  exports.prototype['holders'] = undefined;
  /**
   * How many decimal points the token is divisble to
   * @member {Number} divibility
   */
  exports.prototype['divibility'] = undefined;
  /**
   * Whether new issuances of this token are locked
   * @member {Boolean} lockStatus
   */
  exports.prototype['lockStatus'] = undefined;
  /**
   * Whether the tokesn are aggregatable
   * @member {String} aggregationPolicy
   */
  exports.prototype['aggregationPolicy'] = undefined;
  /**
   * A UTXO of this token
   * @member {String} someUtxo
   */
  exports.prototype['someUtxo'] = undefined;



  return exports;
}));


