/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetTokenMetadataResponseMetadataOfIssuenceData from './GetTokenMetadataResponseMetadataOfIssuenceData';

/**
 * The GetTokenMetadataResponseMetadataOfIssuence model module.
 * @module model/GetTokenMetadataResponseMetadataOfIssuence
 * @version 1.2.1
 */
class GetTokenMetadataResponseMetadataOfIssuence {
    /**
     * Constructs a new <code>GetTokenMetadataResponseMetadataOfIssuence</code>.
     * Metadata set at issuance
     * @alias module:model/GetTokenMetadataResponseMetadataOfIssuence
     */
    constructor() { 
        
        GetTokenMetadataResponseMetadataOfIssuence.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetTokenMetadataResponseMetadataOfIssuence</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTokenMetadataResponseMetadataOfIssuence} obj Optional instance to populate.
     * @return {module:model/GetTokenMetadataResponseMetadataOfIssuence} The populated <code>GetTokenMetadataResponseMetadataOfIssuence</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTokenMetadataResponseMetadataOfIssuence();

            if (data.hasOwnProperty('data')) {
                obj['data'] = GetTokenMetadataResponseMetadataOfIssuenceData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GetTokenMetadataResponseMetadataOfIssuenceData} data
 */
GetTokenMetadataResponseMetadataOfIssuence.prototype['data'] = undefined;






export default GetTokenMetadataResponseMetadataOfIssuence;

