/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetTransactionInfoResponseScriptSig from './GetTransactionInfoResponseScriptSig';

/**
 * The GetTxResponseVin model module.
 * @module model/GetTxResponseVin
 * @version 1.2.1
 */
class GetTxResponseVin {
    /**
     * Constructs a new <code>GetTxResponseVin</code>.
     * @alias module:model/GetTxResponseVin
     */
    constructor() { 
        
        GetTxResponseVin.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetTxResponseVin</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTxResponseVin} obj Optional instance to populate.
     * @return {module:model/GetTxResponseVin} The populated <code>GetTxResponseVin</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTxResponseVin();

            if (data.hasOwnProperty('sequence')) {
                obj['sequence'] = ApiClient.convertToType(data['sequence'], 'Number');
            }
            if (data.hasOwnProperty('scriptSig')) {
                obj['scriptSig'] = GetTransactionInfoResponseScriptSig.constructFromObject(data['scriptSig']);
            }
            if (data.hasOwnProperty('valueSat')) {
                obj['valueSat'] = ApiClient.convertToType(data['valueSat'], 'Number');
            }
            if (data.hasOwnProperty('txid')) {
                obj['txid'] = ApiClient.convertToType(data['txid'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('n')) {
                obj['n'] = ApiClient.convertToType(data['n'], 'Number');
            }
            if (data.hasOwnProperty('vout')) {
                obj['vout'] = ApiClient.convertToType(data['vout'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} sequence
 */
GetTxResponseVin.prototype['sequence'] = undefined;

/**
 * @member {module:model/GetTransactionInfoResponseScriptSig} scriptSig
 */
GetTxResponseVin.prototype['scriptSig'] = undefined;

/**
 * Value of input in NEBL satoshi
 * @member {Number} valueSat
 */
GetTxResponseVin.prototype['valueSat'] = undefined;

/**
 * TXID of the input
 * @member {String} txid
 */
GetTxResponseVin.prototype['txid'] = undefined;

/**
 * Value of input in NEBL
 * @member {Number} value
 */
GetTxResponseVin.prototype['value'] = undefined;

/**
 * input index
 * @member {Number} n
 */
GetTxResponseVin.prototype['n'] = undefined;

/**
 * output index
 * @member {Number} vout
 */
GetTxResponseVin.prototype['vout'] = undefined;






export default GetTxResponseVin;

