/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta from './GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta';

/**
 * The GetTokenMetadataResponseMetadataOfIssuanceDataUserData model module.
 * @module model/GetTokenMetadataResponseMetadataOfIssuanceDataUserData
 * @version 1.2.1
 */
class GetTokenMetadataResponseMetadataOfIssuanceDataUserData {
    /**
     * Constructs a new <code>GetTokenMetadataResponseMetadataOfIssuanceDataUserData</code>.
     * Metadata set by user on token
     * @alias module:model/GetTokenMetadataResponseMetadataOfIssuanceDataUserData
     */
    constructor() { 
        
        GetTokenMetadataResponseMetadataOfIssuanceDataUserData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetTokenMetadataResponseMetadataOfIssuanceDataUserData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTokenMetadataResponseMetadataOfIssuanceDataUserData} obj Optional instance to populate.
     * @return {module:model/GetTokenMetadataResponseMetadataOfIssuanceDataUserData} The populated <code>GetTokenMetadataResponseMetadataOfIssuanceDataUserData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTokenMetadataResponseMetadataOfIssuanceDataUserData();

            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], [GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta>} meta
 */
GetTokenMetadataResponseMetadataOfIssuanceDataUserData.prototype['meta'] = undefined;






export default GetTokenMetadataResponseMetadataOfIssuanceDataUserData;

