/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetTokenMetadataResponseMetadataOfIssuance'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetTokenMetadataResponseMetadataOfIssuance'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.GetTokenMetadataResponse = factory(root.NeblioRestApiSuite.ApiClient, root.NeblioRestApiSuite.GetTokenMetadataResponseMetadataOfIssuance);
  }
}(this, function(ApiClient, GetTokenMetadataResponseMetadataOfIssuance) {
  'use strict';




  /**
   * The GetTokenMetadataResponse model module.
   * @module model/GetTokenMetadataResponse
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>GetTokenMetadataResponse</code>.
   * @alias module:model/GetTokenMetadataResponse
   * @class
   */
  var exports = function() {
    var _this = this;















  };

  /**
   * Constructs a <code>GetTokenMetadataResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetTokenMetadataResponse} obj Optional instance to populate.
   * @return {module:model/GetTokenMetadataResponse} The populated <code>GetTokenMetadataResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tokenId')) {
        obj['tokenId'] = ApiClient.convertToType(data['tokenId'], 'String');
      }
      if (data.hasOwnProperty('divisibility')) {
        obj['divisibility'] = ApiClient.convertToType(data['divisibility'], 'Number');
      }
      if (data.hasOwnProperty('lockStatus')) {
        obj['lockStatus'] = ApiClient.convertToType(data['lockStatus'], 'Boolean');
      }
      if (data.hasOwnProperty('aggregationPolicy')) {
        obj['aggregationPolicy'] = ApiClient.convertToType(data['aggregationPolicy'], 'String');
      }
      if (data.hasOwnProperty('totalSupply')) {
        obj['totalSupply'] = ApiClient.convertToType(data['totalSupply'], 'Number');
      }
      if (data.hasOwnProperty('numOfHolders')) {
        obj['numOfHolders'] = ApiClient.convertToType(data['numOfHolders'], 'Number');
      }
      if (data.hasOwnProperty('numOfTransfers')) {
        obj['numOfTransfers'] = ApiClient.convertToType(data['numOfTransfers'], 'Number');
      }
      if (data.hasOwnProperty('numofIssuance')) {
        obj['numofIssuance'] = ApiClient.convertToType(data['numofIssuance'], 'Number');
      }
      if (data.hasOwnProperty('numOfBurns')) {
        obj['numOfBurns'] = ApiClient.convertToType(data['numOfBurns'], 'Number');
      }
      if (data.hasOwnProperty('firstBlock')) {
        obj['firstBlock'] = ApiClient.convertToType(data['firstBlock'], 'Number');
      }
      if (data.hasOwnProperty('issuanceTxid')) {
        obj['issuanceTxid'] = ApiClient.convertToType(data['issuanceTxid'], 'String');
      }
      if (data.hasOwnProperty('issueAddress')) {
        obj['issueAddress'] = ApiClient.convertToType(data['issueAddress'], 'String');
      }
      if (data.hasOwnProperty('metadataOfIssuance')) {
        obj['metadataOfIssuance'] = GetTokenMetadataResponseMetadataOfIssuance.constructFromObject(data['metadataOfIssuance']);
      }
      if (data.hasOwnProperty('metadataOfUtxo')) {
        obj['metadataOfUtxo'] = GetTokenMetadataResponseMetadataOfIssuance.constructFromObject(data['metadataOfUtxo']);
      }
    }
    return obj;
  }

  /**
   * ID of the token
   * @member {String} tokenId
   */
  exports.prototype['tokenId'] = undefined;
  /**
   * Decimal places the token is divisible to
   * @member {Number} divisibility
   */
  exports.prototype['divisibility'] = undefined;
  /**
   * Whether issuance of more tokens is locked
   * @member {Boolean} lockStatus
   */
  exports.prototype['lockStatus'] = undefined;
  /**
   * Whether the tokens are aggregatable
   * @member {String} aggregationPolicy
   */
  exports.prototype['aggregationPolicy'] = undefined;
  /**
   * Total number of tokens in supply
   * @member {Number} totalSupply
   */
  exports.prototype['totalSupply'] = undefined;
  /**
   * Total number of addresses this token is held at
   * @member {Number} numOfHolders
   */
  exports.prototype['numOfHolders'] = undefined;
  /**
   * Total number of transactions of this token
   * @member {Number} numOfTransfers
   */
  exports.prototype['numOfTransfers'] = undefined;
  /**
   * Total number of times this token has been issued
   * @member {Number} numofIssuance
   */
  exports.prototype['numofIssuance'] = undefined;
  /**
   * Number of times tokens have been burned
   * @member {Number} numOfBurns
   */
  exports.prototype['numOfBurns'] = undefined;
  /**
   * Block number token was issued in
   * @member {Number} firstBlock
   */
  exports.prototype['firstBlock'] = undefined;
  /**
   * TXID the token was issued with
   * @member {String} issuanceTxid
   */
  exports.prototype['issuanceTxid'] = undefined;
  /**
   * Address that issued the tokens
   * @member {String} issueAddress
   */
  exports.prototype['issueAddress'] = undefined;
  /**
   * @member {module:model/GetTokenMetadataResponseMetadataOfIssuance} metadataOfIssuance
   */
  exports.prototype['metadataOfIssuance'] = undefined;
  /**
   * @member {module:model/GetTokenMetadataResponseMetadataOfIssuance} metadataOfUtxo
   */
  exports.prototype['metadataOfUtxo'] = undefined;



  return exports;
}));


