/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetTransactionInfoResponsePreviousOutput from './GetTransactionInfoResponsePreviousOutput';
import GetTransactionInfoResponseTokens from './GetTransactionInfoResponseTokens';

/**
 * The GetTransactionInfoResponseVout model module.
 * @module model/GetTransactionInfoResponseVout
 * @version 1.2.1
 */
class GetTransactionInfoResponseVout {
    /**
     * Constructs a new <code>GetTransactionInfoResponseVout</code>.
     * @alias module:model/GetTransactionInfoResponseVout
     */
    constructor() { 
        
        GetTransactionInfoResponseVout.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetTransactionInfoResponseVout</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTransactionInfoResponseVout} obj Optional instance to populate.
     * @return {module:model/GetTransactionInfoResponseVout} The populated <code>GetTransactionInfoResponseVout</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTransactionInfoResponseVout();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('n')) {
                obj['n'] = ApiClient.convertToType(data['n'], 'Number');
            }
            if (data.hasOwnProperty('scriptPubKey')) {
                obj['scriptPubKey'] = GetTransactionInfoResponsePreviousOutput.constructFromObject(data['scriptPubKey']);
            }
            if (data.hasOwnProperty('tokens')) {
                obj['tokens'] = ApiClient.convertToType(data['tokens'], [GetTransactionInfoResponseTokens]);
            }
            if (data.hasOwnProperty('used')) {
                obj['used'] = ApiClient.convertToType(data['used'], 'Boolean');
            }
            if (data.hasOwnProperty('blockheight')) {
                obj['blockheight'] = ApiClient.convertToType(data['blockheight'], 'Number');
            }
            if (data.hasOwnProperty('usedBlockheight')) {
                obj['usedBlockheight'] = ApiClient.convertToType(data['usedBlockheight'], 'Number');
            }
            if (data.hasOwnProperty('usedTxid')) {
                obj['usedTxid'] = ApiClient.convertToType(data['usedTxid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Value of the output in NEBL satoshi
 * @member {Number} value
 */
GetTransactionInfoResponseVout.prototype['value'] = undefined;

/**
 * Output index
 * @member {Number} n
 */
GetTransactionInfoResponseVout.prototype['n'] = undefined;

/**
 * @member {module:model/GetTransactionInfoResponsePreviousOutput} scriptPubKey
 */
GetTransactionInfoResponseVout.prototype['scriptPubKey'] = undefined;

/**
 * @member {Array.<module:model/GetTransactionInfoResponseTokens>} tokens
 */
GetTransactionInfoResponseVout.prototype['tokens'] = undefined;

/**
 * Whether this output has now been used
 * @member {Boolean} used
 */
GetTransactionInfoResponseVout.prototype['used'] = undefined;

/**
 * Blockheight of this transaction
 * @member {Number} blockheight
 */
GetTransactionInfoResponseVout.prototype['blockheight'] = undefined;

/**
 * Blockheight this output was used in
 * @member {Number} usedBlockheight
 */
GetTransactionInfoResponseVout.prototype['usedBlockheight'] = undefined;

/**
 * TXID this output was used in
 * @member {String} usedTxid
 */
GetTransactionInfoResponseVout.prototype['usedTxid'] = undefined;






export default GetTransactionInfoResponseVout;

