/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.GetTransactionInfoResponsePreviousOutput = factory(root.NeblioRestApiSuite.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetTransactionInfoResponsePreviousOutput model module.
   * @module model/GetTransactionInfoResponsePreviousOutput
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>GetTransactionInfoResponsePreviousOutput</code>.
   * @alias module:model/GetTransactionInfoResponsePreviousOutput
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>GetTransactionInfoResponsePreviousOutput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetTransactionInfoResponsePreviousOutput} obj Optional instance to populate.
   * @return {module:model/GetTransactionInfoResponsePreviousOutput} The populated <code>GetTransactionInfoResponsePreviousOutput</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('asm')) {
        obj['asm'] = ApiClient.convertToType(data['asm'], 'String');
      }
      if (data.hasOwnProperty('hex')) {
        obj['hex'] = ApiClient.convertToType(data['hex'], 'String');
      }
      if (data.hasOwnProperty('reqSigs')) {
        obj['reqSigs'] = ApiClient.convertToType(data['reqSigs'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('addresses')) {
        obj['addresses'] = ApiClient.convertToType(data['addresses'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} asm
   */
  exports.prototype['asm'] = undefined;
  /**
   * @member {String} hex
   */
  exports.prototype['hex'] = undefined;
  /**
   * @member {Number} reqSigs
   */
  exports.prototype['reqSigs'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Array.<String>} addresses
   */
  exports.prototype['addresses'] = undefined;



  return exports;
}));


