/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetTokenMetadataResponseMetadataOfIssuenceDataUserData from './GetTokenMetadataResponseMetadataOfIssuenceDataUserData';

/**
 * The GetTokenMetadataResponseMetadataOfIssuenceData model module.
 * @module model/GetTokenMetadataResponseMetadataOfIssuenceData
 * @version 1.2.1
 */
class GetTokenMetadataResponseMetadataOfIssuenceData {
    /**
     * Constructs a new <code>GetTokenMetadataResponseMetadataOfIssuenceData</code>.
     * @alias module:model/GetTokenMetadataResponseMetadataOfIssuenceData
     */
    constructor() { 
        
        GetTokenMetadataResponseMetadataOfIssuenceData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetTokenMetadataResponseMetadataOfIssuenceData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTokenMetadataResponseMetadataOfIssuenceData} obj Optional instance to populate.
     * @return {module:model/GetTokenMetadataResponseMetadataOfIssuenceData} The populated <code>GetTokenMetadataResponseMetadataOfIssuenceData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTokenMetadataResponseMetadataOfIssuenceData();

            if (data.hasOwnProperty('tokenName')) {
                obj['tokenName'] = ApiClient.convertToType(data['tokenName'], 'String');
            }
            if (data.hasOwnProperty('issuer')) {
                obj['issuer'] = ApiClient.convertToType(data['issuer'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('userData')) {
                obj['userData'] = GetTokenMetadataResponseMetadataOfIssuenceDataUserData.constructFromObject(data['userData']);
            }
        }
        return obj;
    }


}

/**
 * Token symbol
 * @member {String} tokenName
 */
GetTokenMetadataResponseMetadataOfIssuenceData.prototype['tokenName'] = undefined;

/**
 * Name of token issuer
 * @member {String} issuer
 */
GetTokenMetadataResponseMetadataOfIssuenceData.prototype['issuer'] = undefined;

/**
 * Token description
 * @member {String} description
 */
GetTokenMetadataResponseMetadataOfIssuenceData.prototype['description'] = undefined;

/**
 * @member {module:model/GetTokenMetadataResponseMetadataOfIssuenceDataUserData} userData
 */
GetTokenMetadataResponseMetadataOfIssuenceData.prototype['userData'] = undefined;






export default GetTokenMetadataResponseMetadataOfIssuenceData;

