/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetTokenIdResponse model module.
 * @module model/GetTokenIdResponse
 * @version 1.2.1
 */
class GetTokenIdResponse {
    /**
     * Constructs a new <code>GetTokenIdResponse</code>.
     * @alias module:model/GetTokenIdResponse
     */
    constructor() { 
        
        GetTokenIdResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetTokenIdResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetTokenIdResponse} obj Optional instance to populate.
     * @return {module:model/GetTokenIdResponse} The populated <code>GetTokenIdResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetTokenIdResponse();

            if (data.hasOwnProperty('tokenId')) {
                obj['tokenId'] = ApiClient.convertToType(data['tokenId'], 'String');
            }
            if (data.hasOwnProperty('tokenName')) {
                obj['tokenName'] = ApiClient.convertToType(data['tokenName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Unique ID of the token
 * @member {String} tokenId
 */
GetTokenIdResponse.prototype['tokenId'] = undefined;

/**
 * String representing the token Symbol
 * @member {String} tokenName
 */
GetTokenIdResponse.prototype['tokenName'] = undefined;






export default GetTokenIdResponse;

