/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IssueTokenResponse model module.
 * @module model/IssueTokenResponse
 * @version 1.2.1
 */
class IssueTokenResponse {
    /**
     * Constructs a new <code>IssueTokenResponse</code>.
     * @alias module:model/IssueTokenResponse
     */
    constructor() { 
        
        IssueTokenResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IssueTokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssueTokenResponse} obj Optional instance to populate.
     * @return {module:model/IssueTokenResponse} The populated <code>IssueTokenResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssueTokenResponse();

            if (data.hasOwnProperty('tokenId')) {
                obj['tokenId'] = ApiClient.convertToType(data['tokenId'], 'String');
            }
            if (data.hasOwnProperty('txHex')) {
                obj['txHex'] = ApiClient.convertToType(data['txHex'], 'String');
            }
        }
        return obj;
    }


}

/**
 * TokenId of the to be issued token
 * @member {String} tokenId
 */
IssueTokenResponse.prototype['tokenId'] = undefined;

/**
 * Unsigned, raw transaction hex of the transaction to issue the token
 * @member {String} txHex
 */
IssueTokenResponse.prototype['txHex'] = undefined;






export default IssueTokenResponse;

