/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IssueTokenRequestMetadataRulesExpiration', 'model/IssueTokenRequestMetadataRulesFees', 'model/IssueTokenRequestMetadataRulesHolders'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IssueTokenRequestMetadataRulesExpiration'), require('./IssueTokenRequestMetadataRulesFees'), require('./IssueTokenRequestMetadataRulesHolders'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.IssueTokenRequestMetadataRules = factory(root.NeblioRestApiSuite.ApiClient, root.NeblioRestApiSuite.IssueTokenRequestMetadataRulesExpiration, root.NeblioRestApiSuite.IssueTokenRequestMetadataRulesFees, root.NeblioRestApiSuite.IssueTokenRequestMetadataRulesHolders);
  }
}(this, function(ApiClient, IssueTokenRequestMetadataRulesExpiration, IssueTokenRequestMetadataRulesFees, IssueTokenRequestMetadataRulesHolders) {
  'use strict';




  /**
   * The IssueTokenRequestMetadataRules model module.
   * @module model/IssueTokenRequestMetadataRules
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>IssueTokenRequestMetadataRules</code>.
   * Object describing token rules
   * @alias module:model/IssueTokenRequestMetadataRules
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>IssueTokenRequestMetadataRules</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IssueTokenRequestMetadataRules} obj Optional instance to populate.
   * @return {module:model/IssueTokenRequestMetadataRules} The populated <code>IssueTokenRequestMetadataRules</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fees')) {
        obj['fees'] = IssueTokenRequestMetadataRulesFees.constructFromObject(data['fees']);
      }
      if (data.hasOwnProperty('holders')) {
        obj['holders'] = ApiClient.convertToType(data['holders'], [IssueTokenRequestMetadataRulesHolders]);
      }
      if (data.hasOwnProperty('expiration')) {
        obj['expiration'] = IssueTokenRequestMetadataRulesExpiration.constructFromObject(data['expiration']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/IssueTokenRequestMetadataRulesFees} fees
   */
  exports.prototype['fees'] = undefined;
  /**
   * Array of objects describing what addresses can hold the token
   * @member {Array.<module:model/IssueTokenRequestMetadataRulesHolders>} holders
   */
  exports.prototype['holders'] = undefined;
  /**
   * @member {module:model/IssueTokenRequestMetadataRulesExpiration} expiration
   */
  exports.prototype['expiration'] = undefined;



  return exports;
}));


