/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IssueTokenRequestMetadataRulesExpiration model module.
 * @module model/IssueTokenRequestMetadataRulesExpiration
 * @version 1.2.1
 */
class IssueTokenRequestMetadataRulesExpiration {
    /**
     * Constructs a new <code>IssueTokenRequestMetadataRulesExpiration</code>.
     * Object describing expiration rules of the token
     * @alias module:model/IssueTokenRequestMetadataRulesExpiration
     */
    constructor() { 
        
        IssueTokenRequestMetadataRulesExpiration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IssueTokenRequestMetadataRulesExpiration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssueTokenRequestMetadataRulesExpiration} obj Optional instance to populate.
     * @return {module:model/IssueTokenRequestMetadataRulesExpiration} The populated <code>IssueTokenRequestMetadataRulesExpiration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssueTokenRequestMetadataRulesExpiration();

            if (data.hasOwnProperty('validUntil')) {
                obj['validUntil'] = ApiClient.convertToType(data['validUntil'], 'Number');
            }
            if (data.hasOwnProperty('locked')) {
                obj['locked'] = ApiClient.convertToType(data['locked'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Blockheight at wh
 * @member {Number} validUntil
 */
IssueTokenRequestMetadataRulesExpiration.prototype['validUntil'] = undefined;

/**
 * Whether this rule can be modified in future transactions
 * @member {Boolean} locked
 */
IssueTokenRequestMetadataRulesExpiration.prototype['locked'] = undefined;






export default IssueTokenRequestMetadataRulesExpiration;

