/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IssueTokenRequestFlags model module.
 * @module model/IssueTokenRequestFlags
 * @version 1.2.1
 */
class IssueTokenRequestFlags {
    /**
     * Constructs a new <code>IssueTokenRequestFlags</code>.
     * Object representing flags that potentialy modify this transaction
     * @alias module:model/IssueTokenRequestFlags
     */
    constructor() { 
        
        IssueTokenRequestFlags.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IssueTokenRequestFlags</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssueTokenRequestFlags} obj Optional instance to populate.
     * @return {module:model/IssueTokenRequestFlags} The populated <code>IssueTokenRequestFlags</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssueTokenRequestFlags();

            if (data.hasOwnProperty('splitChange')) {
                obj['splitChange'] = ApiClient.convertToType(data['splitChange'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * If true change will be split into 2 outputs, one for NEBL change and one for NTP1 change (recommended)
 * @member {Boolean} splitChange
 */
IssueTokenRequestFlags.prototype['splitChange'] = undefined;






export default IssueTokenRequestFlags;

