/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IssueTokenRequestMetadataUrls model module.
 * @module model/IssueTokenRequestMetadataUrls
 * @version 1.2.1
 */
class IssueTokenRequestMetadataUrls {
    /**
     * Constructs a new <code>IssueTokenRequestMetadataUrls</code>.
     * @alias module:model/IssueTokenRequestMetadataUrls
     */
    constructor() { 
        
        IssueTokenRequestMetadataUrls.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IssueTokenRequestMetadataUrls</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssueTokenRequestMetadataUrls} obj Optional instance to populate.
     * @return {module:model/IssueTokenRequestMetadataUrls} The populated <code>IssueTokenRequestMetadataUrls</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssueTokenRequestMetadataUrls();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('mimeType')) {
                obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
            }
            if (data.hasOwnProperty('dataHash')) {
                obj['dataHash'] = ApiClient.convertToType(data['dataHash'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Name of the URL
 * @member {String} name
 */
IssueTokenRequestMetadataUrls.prototype['name'] = undefined;

/**
 * Actual URL
 * @member {String} url
 */
IssueTokenRequestMetadataUrls.prototype['url'] = undefined;

/**
 * mimeType of URL content
 * @member {String} mimeType
 */
IssueTokenRequestMetadataUrls.prototype['mimeType'] = undefined;

/**
 * Hash of data at the URL, used for verification
 * @member {String} dataHash
 */
IssueTokenRequestMetadataUrls.prototype['dataHash'] = undefined;






export default IssueTokenRequestMetadataUrls;

