/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.IssueTokenRequestFlags = factory(root.NeblioRestApiSuite.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The IssueTokenRequestFlags model module.
   * @module model/IssueTokenRequestFlags
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>IssueTokenRequestFlags</code>.
   * Object representing flags that potentialy modify this transaction
   * @alias module:model/IssueTokenRequestFlags
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>IssueTokenRequestFlags</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IssueTokenRequestFlags} obj Optional instance to populate.
   * @return {module:model/IssueTokenRequestFlags} The populated <code>IssueTokenRequestFlags</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('splitChange')) {
        obj['splitChange'] = ApiClient.convertToType(data['splitChange'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * If true change will be split into 2 outputs, one for NEBL change and one for NTP1 change (recommended)
   * @member {Boolean} splitChange
   */
  exports.prototype['splitChange'] = undefined;



  return exports;
}));


