/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IssueTokenRequestMetadataRulesExpiration from './IssueTokenRequestMetadataRulesExpiration';
import IssueTokenRequestMetadataRulesFees from './IssueTokenRequestMetadataRulesFees';
import IssueTokenRequestMetadataRulesHolders from './IssueTokenRequestMetadataRulesHolders';

/**
 * The IssueTokenRequestMetadataRules model module.
 * @module model/IssueTokenRequestMetadataRules
 * @version 1.2.1
 */
class IssueTokenRequestMetadataRules {
    /**
     * Constructs a new <code>IssueTokenRequestMetadataRules</code>.
     * Object describing token rules
     * @alias module:model/IssueTokenRequestMetadataRules
     */
    constructor() { 
        
        IssueTokenRequestMetadataRules.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IssueTokenRequestMetadataRules</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssueTokenRequestMetadataRules} obj Optional instance to populate.
     * @return {module:model/IssueTokenRequestMetadataRules} The populated <code>IssueTokenRequestMetadataRules</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssueTokenRequestMetadataRules();

            if (data.hasOwnProperty('fees')) {
                obj['fees'] = IssueTokenRequestMetadataRulesFees.constructFromObject(data['fees']);
            }
            if (data.hasOwnProperty('holders')) {
                obj['holders'] = ApiClient.convertToType(data['holders'], [IssueTokenRequestMetadataRulesHolders]);
            }
            if (data.hasOwnProperty('expiration')) {
                obj['expiration'] = IssueTokenRequestMetadataRulesExpiration.constructFromObject(data['expiration']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/IssueTokenRequestMetadataRulesFees} fees
 */
IssueTokenRequestMetadataRules.prototype['fees'] = undefined;

/**
 * Array of objects describing what addresses can hold the token
 * @member {Array.<module:model/IssueTokenRequestMetadataRulesHolders>} holders
 */
IssueTokenRequestMetadataRules.prototype['holders'] = undefined;

/**
 * @member {module:model/IssueTokenRequestMetadataRulesExpiration} expiration
 */
IssueTokenRequestMetadataRules.prototype['expiration'] = undefined;






export default IssueTokenRequestMetadataRules;

