/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.IssueTokenRequestMetadataRulesHolders = factory(root.NeblioRestApiSuite.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The IssueTokenRequestMetadataRulesHolders model module.
   * @module model/IssueTokenRequestMetadataRulesHolders
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>IssueTokenRequestMetadataRulesHolders</code>.
   * @alias module:model/IssueTokenRequestMetadataRulesHolders
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>IssueTokenRequestMetadataRulesHolders</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IssueTokenRequestMetadataRulesHolders} obj Optional instance to populate.
   * @return {module:model/IssueTokenRequestMetadataRulesHolders} The populated <code>IssueTokenRequestMetadataRulesHolders</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('locked')) {
        obj['locked'] = ApiClient.convertToType(data['locked'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Address that can hold the token
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * Whether this rule can be modified in future transactions
   * @member {Boolean} locked
   */
  exports.prototype['locked'] = undefined;



  return exports;
}));


