/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IssueTokenRequestTransfer model module.
 * @module model/IssueTokenRequestTransfer
 * @version 1.2.1
 */
class IssueTokenRequestTransfer {
    /**
     * Constructs a new <code>IssueTokenRequestTransfer</code>.
     * @alias module:model/IssueTokenRequestTransfer
     */
    constructor() { 
        
        IssueTokenRequestTransfer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IssueTokenRequestTransfer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssueTokenRequestTransfer} obj Optional instance to populate.
     * @return {module:model/IssueTokenRequestTransfer} The populated <code>IssueTokenRequestTransfer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssueTokenRequestTransfer();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Address to send the amount of issued tokens to
 * @member {String} address
 */
IssueTokenRequestTransfer.prototype['address'] = undefined;

/**
 * @member {Number} amount
 */
IssueTokenRequestTransfer.prototype['amount'] = undefined;






export default IssueTokenRequestTransfer;

