/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.IssueTokenRequestMetadataEncryptions = factory(root.NeblioRestApiSuite.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The IssueTokenRequestMetadataEncryptions model module.
   * @module model/IssueTokenRequestMetadataEncryptions
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>IssueTokenRequestMetadataEncryptions</code>.
   * @alias module:model/IssueTokenRequestMetadataEncryptions
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>IssueTokenRequestMetadataEncryptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IssueTokenRequestMetadataEncryptions} obj Optional instance to populate.
   * @return {module:model/IssueTokenRequestMetadataEncryptions} The populated <code>IssueTokenRequestMetadataEncryptions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('key')) {
        obj['key'] = ApiClient.convertToType(data['key'], 'String');
      }
      if (data.hasOwnProperty('pubkey')) {
        obj['pubkey'] = ApiClient.convertToType(data['pubkey'], 'String');
      }
      if (data.hasOwnProperty('format')) {
        obj['format'] = ApiClient.convertToType(data['format'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * userData key to encrypt
   * @member {String} key
   */
  exports.prototype['key'] = undefined;
  /**
   * RSA public key used for encryption
   * @member {String} pubkey
   */
  exports.prototype['pubkey'] = undefined;
  /**
   * key format (pem or der)
   * @member {String} format
   */
  exports.prototype['format'] = undefined;
  /**
   * pkcs1 or pkcs8
   * @member {String} type
   */
  exports.prototype['type'] = undefined;



  return exports;
}));


