/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RpcResponse model module.
 * @module model/RpcResponse
 * @version 1.2.1
 */
class RpcResponse {
    /**
     * Constructs a new <code>RpcResponse</code>.
     * Object containing the JSON response from the Neblio node.
     * @alias module:model/RpcResponse
     */
    constructor() { 
        
        RpcResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RpcResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RpcResponse} obj Optional instance to populate.
     * @return {module:model/RpcResponse} The populated <code>RpcResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RpcResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], Object);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], Object);
            }
        }
        return obj;
    }


}

/**
 * Object containing the response output.
 * @member {Object} result
 */
RpcResponse.prototype['result'] = undefined;

/**
 * Identifier of RCP caller
 * @member {String} id
 */
RpcResponse.prototype['id'] = undefined;

/**
 * Object containing any error information.
 * @member {Object} error
 */
RpcResponse.prototype['error'] = undefined;






export default RpcResponse;

