/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RpcRequest model module.
 * @module model/RpcRequest
 * @version 1.2.1
 */
class RpcRequest {
    /**
     * Constructs a new <code>RpcRequest</code>.
     * @alias module:model/RpcRequest
     * @param jsonrpc {String} JSON-RPC version
     * @param id {String} Identifier of RCP caller
     * @param method {String} Name of the Neblio RPC method to call
     * @param params {Array.<String>} Array of string params that should be passed to the RPC method.
     */
    constructor(jsonrpc, id, method, params) { 
        
        RpcRequest.initialize(this, jsonrpc, id, method, params);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jsonrpc, id, method, params) { 
        obj['jsonrpc'] = jsonrpc;
        obj['id'] = id;
        obj['method'] = method;
        obj['params'] = params;
    }

    /**
     * Constructs a <code>RpcRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RpcRequest} obj Optional instance to populate.
     * @return {module:model/RpcRequest} The populated <code>RpcRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RpcRequest();

            if (data.hasOwnProperty('jsonrpc')) {
                obj['jsonrpc'] = ApiClient.convertToType(data['jsonrpc'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('params')) {
                obj['params'] = ApiClient.convertToType(data['params'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * JSON-RPC version
 * @member {String} jsonrpc
 * @default '1.0'
 */
RpcRequest.prototype['jsonrpc'] = '1.0';

/**
 * Identifier of RCP caller
 * @member {String} id
 * @default 'neblio-apis'
 */
RpcRequest.prototype['id'] = 'neblio-apis';

/**
 * Name of the Neblio RPC method to call
 * @member {String} method
 */
RpcRequest.prototype['method'] = undefined;

/**
 * Array of string params that should be passed to the RPC method.
 * @member {Array.<String>} params
 */
RpcRequest.prototype['params'] = undefined;






export default RpcRequest;

