/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IssueTokenRequestFlags from './IssueTokenRequestFlags';
import IssueTokenRequestMetadata from './IssueTokenRequestMetadata';
import SendTokenRequestTo from './SendTokenRequestTo';

/**
 * The SendTokenRequest model module.
 * @module model/SendTokenRequest
 * @version 1.2.1
 */
class SendTokenRequest {
    /**
     * Constructs a new <code>SendTokenRequest</code>.
     * @alias module:model/SendTokenRequest
     * @param fee {Number} Fee in satoshi to include in the issuance transaction min 10000 (0.0001 NEBL)
     * @param to {Array.<module:model/SendTokenRequestTo>} 
     */
    constructor(fee, to) { 
        
        SendTokenRequest.initialize(this, fee, to);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fee, to) { 
        obj['fee'] = fee;
        obj['to'] = to;
    }

    /**
     * Constructs a <code>SendTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendTokenRequest} obj Optional instance to populate.
     * @return {module:model/SendTokenRequest} The populated <code>SendTokenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendTokenRequest();

            if (data.hasOwnProperty('fee')) {
                obj['fee'] = ApiClient.convertToType(data['fee'], 'Number');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], ['String']);
            }
            if (data.hasOwnProperty('sendutxo')) {
                obj['sendutxo'] = ApiClient.convertToType(data['sendutxo'], ['String']);
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], [SendTokenRequestTo]);
            }
            if (data.hasOwnProperty('flags')) {
                obj['flags'] = IssueTokenRequestFlags.constructFromObject(data['flags']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = IssueTokenRequestMetadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }


}

/**
 * Fee in satoshi to include in the issuance transaction min 10000 (0.0001 NEBL)
 * @member {Number} fee
 */
SendTokenRequest.prototype['fee'] = undefined;

/**
 * Array of addresses to send the token from
 * @member {Array.<String>} from
 */
SendTokenRequest.prototype['from'] = undefined;

/**
 * Array of UTXOs to send the token from
 * @member {Array.<String>} sendutxo
 */
SendTokenRequest.prototype['sendutxo'] = undefined;

/**
 * @member {Array.<module:model/SendTokenRequestTo>} to
 */
SendTokenRequest.prototype['to'] = undefined;

/**
 * @member {module:model/IssueTokenRequestFlags} flags
 */
SendTokenRequest.prototype['flags'] = undefined;

/**
 * @member {module:model/IssueTokenRequestMetadata} metadata
 */
SendTokenRequest.prototype['metadata'] = undefined;






export default SendTokenRequest;

