/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IssueTokenRequestMetadata', 'model/SendTokenRequestTo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IssueTokenRequestMetadata'), require('./SendTokenRequestTo'));
  } else {
    // Browser globals (root is window)
    if (!root.NeblioRestApiSuite) {
      root.NeblioRestApiSuite = {};
    }
    root.NeblioRestApiSuite.SendTokenRequest = factory(root.NeblioRestApiSuite.ApiClient, root.NeblioRestApiSuite.IssueTokenRequestMetadata, root.NeblioRestApiSuite.SendTokenRequestTo);
  }
}(this, function(ApiClient, IssueTokenRequestMetadata, SendTokenRequestTo) {
  'use strict';




  /**
   * The SendTokenRequest model module.
   * @module model/SendTokenRequest
   * @version 1.1.1
   */

  /**
   * Constructs a new <code>SendTokenRequest</code>.
   * @alias module:model/SendTokenRequest
   * @class
   * @param fee {Number} Fee in satoshi to include in the issuance transaction min 10000 (0.0001 NEBL)
   * @param to {Array.<module:model/SendTokenRequestTo>} 
   */
  var exports = function(fee, to) {
    var _this = this;

    _this['fee'] = fee;

    _this['to'] = to;

  };

  /**
   * Constructs a <code>SendTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SendTokenRequest} obj Optional instance to populate.
   * @return {module:model/SendTokenRequest} The populated <code>SendTokenRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fee')) {
        obj['fee'] = ApiClient.convertToType(data['fee'], 'Number');
      }
      if (data.hasOwnProperty('from')) {
        obj['from'] = ApiClient.convertToType(data['from'], ['String']);
      }
      if (data.hasOwnProperty('to')) {
        obj['to'] = ApiClient.convertToType(data['to'], [SendTokenRequestTo]);
      }
      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = IssueTokenRequestMetadata.constructFromObject(data['metadata']);
      }
    }
    return obj;
  }

  /**
   * Fee in satoshi to include in the issuance transaction min 10000 (0.0001 NEBL)
   * @member {Number} fee
   */
  exports.prototype['fee'] = undefined;
  /**
   * Array of addresses to send the token from
   * @member {Array.<String>} from
   */
  exports.prototype['from'] = undefined;
  /**
   * @member {Array.<module:model/SendTokenRequestTo>} to
   */
  exports.prototype['to'] = undefined;
  /**
   * @member {module:model/IssueTokenRequestMetadata} metadata
   */
  exports.prototype['metadata'] = undefined;



  return exports;
}));


