/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendTxRequest model module.
 * @module model/SendTxRequest
 * @version 1.2.1
 */
class SendTxRequest {
    /**
     * Constructs a new <code>SendTxRequest</code>.
     * @alias module:model/SendTxRequest
     */
    constructor() { 
        
        SendTxRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendTxRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendTxRequest} obj Optional instance to populate.
     * @return {module:model/SendTxRequest} The populated <code>SendTxRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendTxRequest();

            if (data.hasOwnProperty('txHex')) {
                obj['txHex'] = ApiClient.convertToType(data['txHex'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Signed raw tx hex to broadcast
 * @member {String} txHex
 */
SendTxRequest.prototype['txHex'] = undefined;






export default SendTxRequest;

