/**
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Neblioapi);
  }
}(this, function(expect, Neblioapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Neblioapi.GetAddressResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetAddressResponse', function() {
    it('should create an instance of GetAddressResponse', function() {
      // uncomment below and update the code to test GetAddressResponse
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be.a(Neblioapi.GetAddressResponse);
    });

    it('should have the property addrStr (base name: "addrStr")', function() {
      // uncomment below and update the code to test the property addrStr
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

    it('should have the property balance (base name: "balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

    it('should have the property balanceSat (base name: "balanceSat")', function() {
      // uncomment below and update the code to test the property balanceSat
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

    it('should have the property totalReceived (base name: "totalReceived")', function() {
      // uncomment below and update the code to test the property totalReceived
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

    it('should have the property totalReceivedSat (base name: "totalReceivedSat")', function() {
      // uncomment below and update the code to test the property totalReceivedSat
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

    it('should have the property totalSent (base name: "totalSent")', function() {
      // uncomment below and update the code to test the property totalSent
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

    it('should have the property totalSentSat (base name: "totalSentSat")', function() {
      // uncomment below and update the code to test the property totalSentSat
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

    it('should have the property unconfirmedBalance (base name: "unconfirmedBalance")', function() {
      // uncomment below and update the code to test the property unconfirmedBalance
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

    it('should have the property unconfirmedBalanceSat (base name: "unconfirmedBalanceSat")', function() {
      // uncomment below and update the code to test the property unconfirmedBalanceSat
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

    it('should have the property unconfirmedTxAppearances (base name: "unconfirmedTxAppearances")', function() {
      // uncomment below and update the code to test the property unconfirmedTxAppearances
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

    it('should have the property txAppearances (base name: "txAppearances")', function() {
      // uncomment below and update the code to test the property txAppearances
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

    it('should have the property transactions (base name: "transactions")', function() {
      // uncomment below and update the code to test the property transactions
      //var instane = new Neblioapi.GetAddressResponse();
      //expect(instance).to.be();
    });

  });

}));
